# Generated by Django 5.2.15 on 2026-06-04 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "current_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "experience_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "experience_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("experience_summary", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("reviewed", "Reviewed"),
                            ("open_to_work", "Open to Work"),
                            ("not_interested", "Not Interested"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
