# Generated by Django 5.2.15 on 2026-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_award_certification_projecthistory_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="surname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
