# Generated by Django 5.2.15 on 2026-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="llm_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
